name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build docs
        run: |
          npm ci
          npm run docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: dist/
